version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: pruebacrud
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data: